version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres-dev
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
    volumes:
      - postgresql:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgresql:
    external: true
